# Generated by Django 4.0.6 on 2022-07-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0002_alter_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='document/skai'),
        ),
        migrations.CreateModel(
            name='MacroFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MacroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prk', models.CharField(max_length=100)),
                ('no_program', models.PositiveIntegerField()),
                ('no_ruptl', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('fungsi', models.CharField(max_length=100)),
                ('sub_fungsi', models.CharField(max_length=100)),
                ('program_utama', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=2)),
                ('jenis_program', models.CharField(max_length=100)),
                ('kegiatan_no', models.PositiveIntegerField()),
                ('kegiatan_uraian', models.TextField()),
                ('kegiatan_target_fisik', models.CharField(max_length=10)),
                ('kegiatan_satuan', models.CharField(max_length=10)),
                ('kegiatan_anggaran', models.IntegerField()),
                ('realisasi_pembayaran', models.IntegerField()),
                ('prediksi_pembayaran', models.IntegerField()),
                ('ai_this_year', models.IntegerField()),
                ('aki_this_year', models.IntegerField()),
                ('aki_n1_year', models.IntegerField()),
                ('aki_n2_year', models.IntegerField()),
                ('aki_n3_year', models.IntegerField()),
                ('aki_n4_year', models.IntegerField()),
                ('aki_after_n1_year', models.IntegerField()),
                ('sumber_dana', models.IntegerField()),
                ('macro_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.macrofile')),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_file_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_before', to='document.macrofile')),
                ('macro_file_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro_after', to='document.macrofile')),
            ],
        ),
    ]
