# Generated by Django 4.0.6 on 2022-07-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_file_macrofile_macrodata_macro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macrodata',
            old_name='kegiatan_anggaran',
            new_name='ang_nilai',
        ),
        migrations.RenameField(
            model_name='macrodata',
            old_name='kegiatan_no',
            new_name='keg_no',
        ),
        migrations.RenameField(
            model_name='macrodata',
            old_name='kegiatan_satuan',
            new_name='keg_satuan',
        ),
        migrations.RenameField(
            model_name='macrodata',
            old_name='kegiatan_target_fisik',
            new_name='keg_target_fisik',
        ),
        migrations.RenameField(
            model_name='macrodata',
            old_name='kegiatan_uraian',
            new_name='keg_uraian',
        ),
        migrations.AddField(
            model_name='macrodata',
            name='ang_jenis_kontrak',
            field=models.CharField(default='Pusat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macrodata',
            name='ang_no_kontrak',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macrodata',
            name='ang_status',
            field=models.CharField(default='Murni', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sumber_dana',
            field=models.CharField(max_length=100),
        ),
    ]
