# Generated by Django 4.0.6 on 2022-07-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_rename_kegiatan_anggaran_macrodata_ang_nilai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='score',
            field=models.CharField(max_length=5),
        ),
    ]
