# Generated by Django 4.0.6 on 2022-07-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_macrodata_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='docaddedskai',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.macro'),
        ),
        migrations.AddField(
            model_name='docskai',
            name='macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.macro'),
        ),
    ]
