# Generated by Django 4.0.6 on 2022-07-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_docaddedskai_macro_docskai_macro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocAddedSKAI',
        ),
    ]
