# Generated by Django 4.0.6 on 2022-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_docskai_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='docskai',
            name='type',
            field=models.CharField(default='Penetapan', max_length=50),
        ),
        migrations.AlterField(
            model_name='docskai',
            name='revision',
            field=models.BooleanField(default=False),
        ),
    ]
