# Generated by Django 4.0.6 on 2022-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_docskai_type_alter_docskai_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='docskai',
            name='macro_doc',
            field=models.FileField(blank=True, null=True, upload_to='document/macro'),
        ),
    ]
