# Generated by Django 4.0.6 on 2022-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_docskai_macro_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docskai',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='docskai',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='macrofile',
            name='uploader',
        ),
        migrations.AddField(
            model_name='docskai',
            name='keyword',
            field=models.CharField(default='SKAI', max_length=100),
        ),
    ]
