# Generated by Django 4.0.6 on 2022-08-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_remove_docskai_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='ai_this_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_after_n1_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n1_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n2_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n3_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n4_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_this_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_jenis_kontrak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_nilai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_no_kontrak',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='cluster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='fungsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jenis_program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_satuan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_target_fisik',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_uraian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='no_prk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='no_program',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='no_ruptl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='prediksi_pembayaran',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='program_utama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='realisasi_pembayaran',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='score',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sub_fungsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sumber_dana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
