# Generated by Django 4.0.6 on 2022-08-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_alter_macrodata_apr_progress_fisik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='ai_this_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_this_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_jenis_kontrak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_no_kontrak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='apr_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='apr_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aug_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aug_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='cluster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='des_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='des_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='feb_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='feb_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='fungsi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jan_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jan_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jenis_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jul_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jul_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jun_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='jun_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_satuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='keg_target_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='mar_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='mar_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='mei_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='mei_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='no_prk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='no_ruptl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='nov_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='nov_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='okt_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='okt_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='program_utama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='rencana_terkontrak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sep_progress_fisik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sep_rencana_disburse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sub_fungsi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='sumber_dana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
