# Generated by Django 4.0.6 on 2022-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_macrodata_ai_this_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='aki_after_n1_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n1_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n2_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n3_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='aki_n4_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_nilai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='ang_no_kontrak',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='prediksi_pembayaran',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrodata',
            name='realisasi_pembayaran',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
