# Generated by Django 4.0.6 on 2022-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_alter_macrodata_aki_after_n1_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docskai',
            name='lrpa_include',
            field=models.BooleanField(default=False),
        ),
    ]
