# Generated by Django 4.0.6 on 2022-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_docskai_lrpa_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prk', models.CharField(max_length=255, unique=True)),
                ('no_program', models.PositiveIntegerField(blank=True, null=True)),
                ('no_ruptl', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.CharField(blank=True, max_length=255, null=True)),
                ('fungsi', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_fungsi', models.CharField(blank=True, max_length=255, null=True)),
                ('program_utama', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_program', models.CharField(blank=True, max_length=255, null=True)),
                ('keg_no', models.PositiveIntegerField(blank=True, null=True)),
                ('keg_uraian', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
