# Generated by Django 4.0.6 on 2022-08-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_prk'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrodata',
            name='prk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.prk'),
        ),
        migrations.AddField(
            model_name='prk',
            name='kode_bpo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prk',
            name='kode_prk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prk',
            name='rekap_user_induk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prk',
            name='upp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
