# Generated by Django 4.0.6 on 2022-09-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_prkdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prkdata',
            old_name='file',
            new_name='file_mou',
        ),
    ]
