# Generated by Django 4.0.6 on 2022-08-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LRPA_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('for_month', models.IntegerField()),
                ('for_year', models.IntegerField()),
                ('no_prk', models.CharField(blank=True, max_length=100, null=True)),
                ('disburse_year_before', models.CharField(blank=True, max_length=100, null=True)),
                ('jan_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('jan_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('feb_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('feb_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('mar_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('mar_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('apr_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('apr_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('mei_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('mei_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('jun_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('jun_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('jul_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('jul_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('aug_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('aug_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('sep_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('sep_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('okt_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('okt_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('nov_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('nov_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('des_rencana_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('des_realisasi_disburse', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
