# Generated by Django 4.0.6 on 2022-08-12 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrpa_monitoring',
            name='file_export_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
