# Generated by Django 4.0.6 on 2022-08-12 07:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monev', '0002_lrpa_monitoring_file_export_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lrpa_monitoring',
            name='file_export_date',
        ),
        migrations.RemoveField(
            model_name='lrpa_monitoring',
            name='for_month',
        ),
        migrations.RemoveField(
            model_name='lrpa_monitoring',
            name='for_year',
        ),
        migrations.RemoveField(
            model_name='lrpa_monitoring',
            name='upload_by',
        ),
        migrations.RemoveField(
            model_name='lrpa_monitoring',
            name='upload_date',
        ),
        migrations.CreateModel(
            name='LRPA_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrpa_file', models.FileField(upload_to='monev/lrpa')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_export_date', models.DateField(default=datetime.date.today)),
                ('for_month', models.IntegerField()),
                ('for_year', models.IntegerField()),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lrpa_monitoring',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monev.lrpa_file'),
        ),
    ]
