# Generated by Django 4.0.6 on 2022-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0003_remove_lrpa_monitoring_file_export_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrpa_monitoring',
            name='mekanisme_pembayaran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
