# Generated by Django 4.0.6 on 2022-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0004_lrpa_monitoring_mekanisme_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrpa_monitoring',
            name='ai_this_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lrpa_monitoring',
            name='aki_this_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lrpa_file',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
