# Generated by Django 4.0.6 on 2022-08-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0006_assigned_prk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRK_Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prk', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_prk', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_bpo', models.CharField(blank=True, max_length=100, null=True)),
                ('rekap_user_induk', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monev.assigned_prk')),
            ],
        ),
    ]
