# Generated by Django 4.0.6 on 2022-08-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0007_prk_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='prk_lookup',
            name='upp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
