# Generated by Django 4.0.6 on 2022-08-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0009_moupengalihandata_filemoupengalihan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemoupengalihan',
            old_name='file',
            new_name='mou_file',
        ),
    ]
