# Generated by Django 4.0.6 on 2022-08-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monev', '0010_rename_file_filemoupengalihan_mou_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moupengalihandata',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monev.filemoupengalihan'),
        ),
    ]
