# Generated by Django 4.0.6 on 2022-09-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomposition', '0002_usulanperiod_usulanrekomposisi_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanrekomposisidata',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
