# Generated by Django 4.0.6 on 2022-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomposition', '0003_usulanrekomposisidata_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanrekomposisi',
            name='is_data_created',
            field=models.BooleanField(default=False),
        ),
    ]
