# Generated by Django 4.0.6 on 2022-09-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomposition', '0004_usulanrekomposisi_is_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulanperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usulanperiod',
            name='for_rekom_akb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usulanperiod',
            name='for_rekom_aki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usulanperiod',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
