# Generated by Django 4.0.6 on 2022-09-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_rename_file_prkdata_file_mou'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomposition', '0005_usulanperiod_created_by_usulanperiod_for_rekom_akb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsulanRekomposisiAKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_data_created', models.BooleanField(default=False)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomposition.usulanperiod')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsulanRekomposisiAKIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('mei', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sep', models.IntegerField(blank=True, null=True)),
                ('okt', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('des', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_changed', models.BooleanField(default=False)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomposition.usulanrekomposisiaki')),
                ('prk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.prk')),
            ],
        ),
        migrations.RemoveField(
            model_name='usulanrekomposisidata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='usulanrekomposisidata',
            name='prk',
        ),
        migrations.DeleteModel(
            name='UsulanRekomposisi',
        ),
        migrations.DeleteModel(
            name='UsulanRekomposisiData',
        ),
    ]
