# Generated by Django 4.0.6 on 2022-10-12 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0022_rename_file_prkdata_file_mou'),
        ('recomposition', '0006_usulanrekomposisiaki_usulanrekomposisiakidata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsulanRekomposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('revisi', models.CharField(default='AKI', max_length=3)),
                ('is_data_created', models.BooleanField(default=False)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomposition.usulanperiod')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UsulanRekomposisiAKIData',
            new_name='UsulanRekomposisiData',
        ),
        migrations.DeleteModel(
            name='UsulanRekomposisiAKI',
        ),
        migrations.AlterField(
            model_name='usulanrekomposisidata',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomposition.usulanrekomposisi'),
        ),
    ]
