# Generated by Django 4.0.6 on 2022-10-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomposition', '0007_usulanrekomposisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbudgetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='monev/ebudget')),
            ],
        ),
    ]
