# Generated by Django 4.0.6 on 2022-10-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomposition', '0008_ebudgetfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbudgetFileOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='monev/ebudget/output')),
            ],
        ),
    ]
