# Generated by Django 4.0.6 on 2022-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.TextField()),
                ('field3', models.IntegerField()),
                ('field4', models.CharField(max_length=100)),
            ],
        ),
    ]
