# Generated by Django 4.0.6 on 2022-07-20 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
