# Generated by Django 4.0.6 on 2022-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_dummytable_dummy_file_alter_dummyfileupload_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyfileupload',
            name='submission',
            field=models.CharField(default='Telah Disetujui', max_length=100),
        ),
    ]
