from django.db import models
from datetime import date
from account.models import Account

class LRPA_Monitoring(models.Model):
    upload_date             = models.DateField(auto_now_add=True)
    upload_by               = models.ForeignKey(Account, on_delete=models.CASCADE)
    file_export_date        = models.DateField(default=date.today)
    for_month               = models.IntegerField()
    for_year                = models.IntegerField()
    no_prk                  = models.CharField(max_length=100, blank=True, null=True)
    disburse_year_before    = models.CharField(max_length=100, blank=True, null=True)
    jan_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    jan_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    feb_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    feb_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    mar_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    mar_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    apr_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    apr_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    mei_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    mei_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    jun_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    jun_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    jul_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    jul_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    aug_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    aug_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    sep_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    sep_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    okt_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    okt_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    nov_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    nov_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
    des_rencana_disburse    = models.CharField(max_length=100, blank=True, null=True)
    des_realisasi_disburse  = models.CharField(max_length=100, blank=True, null=True)
