from django.db import models

class LRPA_Monitoring(models.Model):
    upload_date             = models.DateField(auto_now_add=True)
    for_month               = models.IntegerField()
    for_year                = models.IntegerField()
    no_prk                  = models.CharField(max_length=100, blank=True, null=True)
    disburse_year_before    = models.IntegerField()
    jan_rencana_disburse    = models.IntegerField()
    jan_realisasi_disburse  = models.IntegerField()
    feb_rencana_disburse    = models.IntegerField()
    feb_realisasi_disburse  = models.IntegerField()
    mar_rencana_disburse    = models.IntegerField()
    mar_realisasi_disburse  = models.IntegerField()
    apr_rencana_disburse    = models.IntegerField()
    apr_realisasi_disburse  = models.IntegerField()
    mei_rencana_disburse    = models.IntegerField()
    mei_realisasi_disburse  = models.IntegerField()
    jun_rencana_disburse    = models.IntegerField()
    jun_realisasi_disburse  = models.IntegerField()
    jul_rencana_disburse    = models.IntegerField()
    jul_realisasi_disburse  = models.IntegerField()
    aug_rencana_disburse    = models.IntegerField()
    aug_realisasi_disburse  = models.IntegerField()
    sep_rencana_disburse    = models.IntegerField()
    sep_realisasi_disburse  = models.IntegerField()
    okt_rencana_disburse    = models.IntegerField()
    okt_realisasi_disburse  = models.IntegerField()
    nov_rencana_disburse    = models.IntegerField()
    nov_realisasi_disburse  = models.IntegerField()
    des_rencana_disburse    = models.IntegerField()
    des_realisasi_disburse  = models.IntegerField()
